runmode: debug                 # 开发模式, debug, release, test
addr: :8080                 # HTTP绑定端口
name: gdrc_hr              # API Server的名字
url: http://0.0.0.0:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
default_password : '000000'
company: 
  name: "揭东农商银行"
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: stdout,file
  logger_level: DEBUG
  logger_file: log/gdrc_hr.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_gdrc_hr
  addr: 127.0.0.1
  port: 5432
  username: elone
  password: 123456
docker_db:
  name: db_gdrc_hr
  addr: 127.0.0.1
  port: 5432
  username: elone
  password: 123456
admin:
  email: 'admin@admin.com'
  username: 'admin'
  password: '123456'

